### ISSUE TITLE
how to solve this problem by ruby filter

### ISSUE THREAD

**Issue by zhangchao2015** [logstash-plugins/logstash-filter-ruby#13] opened 2015-11-25 12:55 UTC
My problem is specific as below.
the event message is:
`{"a":[{"aa":"v1"},{"bb":"v2"}]}`
how to add a field ,namely, "a_size" and its value is array a's length. so the output is like below:
`{"a":[{"aa":"v1"},{"bb":"v2"}],"a_size":2 }`

**Comment by untergeek** [comment] 2015-11-25 16:04
This is not a bug report, but a usage question.  Please close this ticket and ask your question at https://discuss.elastic.co/c/logstash

**Closed** 2015-12-14 04:57 UTC
