### ISSUE TITLE
Memory leak when utilizing ruby{} block in a filter, any suggestions to fix?

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-ruby#8] opened 2015-05-17 23:56 UTC
(This issue was originally filed by @PeterGrace at https://github.com/elastic/logstash/issues/2413)

---

Hi there,

utilizing the filter block, below, I have a reproducible memory leak in my configuration.  This only started yesterday when I changed my assignments to ||= to remove a repetitive warning that a constant was already defined.  Can anyone shed some light on why this code might be causing a memory leak?

```
filter {
        ruby {
            code => "
                require 'socket'
                CollectorName ||= Socket::gethostname
                FieldName ||= 'collector'
                event[FieldName] = CollectorName
                "
        }
}
```

**Comment by vanga** [comment] 2016-10-18 02:08
I believe I am facing this too. 

any suggestions on who to debug it?

I have config with around 10 blocks like this 

```
     if [x] {
        ruby {            
              code => "event['Avg_x'] = event['x'].to_f / 1000"      
           }    
      }
```

**Comment by vanga** [comment] 2016-10-18 12:28
I looked at the jmap output and I see this `[B` as the top class name with most memory.

can some one tell me what that class is related to?

Logstash version is 2.4.0
Logstash filter version 2.0.5

I have tried similar config with ruby filter in a different environment, I can't reproduce the memory issue though.

**Comment by jsvd** [comment] 2018-05-08 10:29
I can't reproduce this anymore with logstash 6.x or even logstash 2.4.1, closing. Please reopen if you're still seeing this issue.

**Closed by jsvd** 2018-05-08 10:29 UTC
